version: 2
models:
  - name: player_awards
    description: >-
      This table contains all the awards received by the NBA players from
      1946 - 2023. Sourced from the NBA API.  This data set comes from the
      official NBA API. You can learn more here: https://github.com/swar/nba_api
    columns:
      - name: player_id
        description: Unique identifier for the player.
        meta:
          dimension:
            type: number
      - name: player_name
        description: Player's full name.
        meta:
          dimension:
            type: string
      - name: award
        description: Name of the award.
        meta:
          dimension:
            type: string
      - name: all_nba_team_number
        description: All-NBA team number. The numbers 1, 2, 3 correspond to first, second and third team.
        meta:
          dimension:
            type: number
      - name: month
        description: Month when the award was given. Applicable for monthly awards only.
        meta:
          dimension:
            type: timestamp
      - name: week
        description: Week when the award was given. Applicable for weekly awards only.
        meta:
          dimension:
            type: timestamp
